"""Generate the release's module category database and Unicode normalization tables."""
import json
import re
import unicodedata as ud
from pathlib import Path


def lua(value):
    if isinstance(value, str):
        return '"' + ''.join('\\%03d' % ord(c) if ord(c) < 32 else '\\' + c if c in '\\"' else c for c in value) + '"'
    if value is None:
        return 'nil'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (float, int)):
        return str(value)
    if isinstance(value, list):
        return '{' + ','.join(map(lua, value)) + '}'
    return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in value.items()) + '}'


def build(root):
    root = Path(root)
    source = json.loads((root / 'data/mod_fingerprints.json').read_text())
    rows = [m for m in source['mods'] if m.get('name') and m.get('author')]
    taxonomy = json.loads((root / 'data/mod_categories.json').read_text())
    categories = taxonomy['categories']
    (root / 'Scripts/mcs_taxonomy_data.lua').write_text('-- Generated by tools/build_mod_fingerprints.py.\nreturn ' + lua(taxonomy) + '\n')
    identifiers = [c['id'] for c in categories]
    if len(set(identifiers)) != len(identifiers) or 'other' not in identifiers:
        raise ValueError('Category identifiers must be unique and include other')
    if any(not re.fullmatch('[a-z]+', c['id']) or not c['description'] for c in categories):
        raise ValueError('Categories require one-word identifiers and descriptions')
    modules = []
    for row in rows:
        # Broad Nexus categories such as Gameplay do not establish a code purpose.
        selections = row.get('assigned_categories')
        category = row.get('assigned_category') or 'other'
        selections = selections or [category]
        selections = list(dict.fromkeys(selections))
        if not 1 <= len(selections) <= taxonomy['max_categories'] or any(c not in identifiers for c in selections):
            raise ValueError(f'Invalid module categories: {selections}')
        if category not in identifiers:
            raise ValueError(f'Unknown category identifier: {category}')
        fingerprints = [{k: f[k] for k in ('kind', 'values', 'group', 'strength')}
                        for f in row.get('fingerprint', [])]
        fingerprints += [
            {'kind':'author-v1','values':[row['author']], 'group':'author','strength':'identity_author'},
            {'kind':'mod-link-v1','values':[f"https://www.nexusmods.com/thebloodofdawnwalker/mods/{row['id']}"],
             'group':'mod_link','strength':'identity_link'}]
        modules.append({'id': row['id'], 'name': row['name'], 'author': row['author'],
                        'category': identifiers.index(selections[0]) + 1, 'categories': selections, 'fingerprints': fingerprints})
    database = {'version': 1, 'categories': categories, 'modules': modules,
                'coverage_complete': source['coverage']['complete']}
    catalog = dict(database, unresolved=[{'id':m['id'], 'name':m.get('name'), 'author':m.get('author'),
                    'status':'metadata_incomplete'} for m in source['mods'] if not (m.get('name') and m.get('author'))])
    (root / 'data/mod_catalog.json').write_text(json.dumps(catalog, ensure_ascii=False, indent=2)+'\n')
    (root / 'Scripts/mod_fingerprints.lua').write_text('-- Generated by tools/build_mod_fingerprints.py.\nreturn ' + lua(database) + '\n')
    # Python and Lua use the same Unicode data to reproduce the experiment's
    # NFC -> casefold -> whitespace normalization, including non-ASCII titles.
    decomposition, combining, folding, composition = {}, {}, {}, {}
    alnum, spaces = [], {}
    begin = None
    for cp in range(0x110000):
        char = chr(cp)
        raw = ud.decomposition(char)
        if raw and not raw.startswith('<'):
            parts = [int(x, 16) for x in raw.split()]
            decomposition[cp] = parts
            if len(parts) == 2 and ud.normalize('NFC', ''.join(map(chr, parts))) == char:
                composition.setdefault(parts[0], {})[parts[1]] = cp
        if ud.combining(char):
            combining[cp] = ud.combining(char)
        if char.casefold() != char:
            folding[cp] = list(map(ord, char.casefold()))
        if char.isspace():
            spaces[cp] = True
        if char.isalnum() and begin is None:
            begin = cp
        elif not char.isalnum() and begin is not None:
            alnum.append([begin, cp - 1]); begin = None
    if begin is not None:
        alnum.append([begin, 0x10ffff])
    tables = {'version': ud.unidata_version, 'decomposition': decomposition, 'combining': combining,
              'folding': folding, 'composition': composition, 'alnum': alnum, 'spaces': spaces}
    (root / 'Scripts/mcs_fingerprint_unicode.lua').write_text('-- Generated Unicode data.\nreturn ' + lua(tables) + '\n')
    return database


if __name__ == '__main__':
    print(len(build(Path(__file__).resolve().parents[1])['modules']), 'module records generated')
